FROM ruby:2.7

WORKDIR /app

ADD ./lib/sidekiq_status/version.rb /app/lib/sidekiq_status/
ADD ./exe/sidekiq_status /app/exe/
ADD ./sidekiq_status.gemspec /app
ADD ./Gemfile /app

RUN bundle install

ADD ./ /app

# install the gem locally
RUN rake install

CMD ["bundle", "exec", "foreman", "start"]