#!/usr/bin/env ruby

# frozen_string_literal: true

require 'sidekiq-r'

require 'pry' if ENV.fetch('USE_PRY', false)

# main entry point
begin
  case ARGV[0]
  when '-a', '--alive'
    SidekiqR.alive?
  when '-r', '--report'
    SidekiqR.status(ARGV[1])
  when '-h', '--help'
    SidekiqR.print_usage
  else
    puts
    puts 'Uknown command, use --help for usage details'
    puts
  end
rescue SidekiqR::Error, Redis::CannotConnectError, Redis::TimeoutError => e
  puts "Error: #{e.message}"
  puts
  exit(1)
end
