#!/usr/bin/env ruby

# frozen_string_literal: true

require 'sidekiq-err'

require 'pry' if ENV.fetch('USE_PRY', false)

# main entry point
begin
  case ARGV[0]
  when '-a', '--alive'
    SidekiqErr.alive?
  when '-r', '--report'
    SidekiqErr.status(ARGV[1])
  when '-h', '--help'
    SidekiqErr.print_usage
  else
    puts
    puts 'Uknown command, use --help for usage details'
    puts
  end
rescue SidekiqErr::Error, Redis::CannotConnectError, Redis::TimeoutError => e
  puts "Error: #{e.message}"
  puts
  exit(1)
end
